spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:mysql://localhost:3306/dbname}
    username: ${DATABASE_USER:hogehoge}
    password: ${DATABASE_PASSWORD:fugafuga}
  jackson:
    dateFormat: yyyy/MM/dd HH:mm:ss
    time-zone: Asia/Tokyo
  session:
    store-type: jdbc
    jdbc:
      table-name: t_session
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
  social:
    facebook:
      appId: ${CHEESE_FACEBOOK_APP_ID:}
      appSecret: ${CHEESE_FACEBOOK_APP_SECRET:}
      redirectUri: ${CHEESE_FACEBOOK_REDIRECT_URL:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${CHEESE_MAIL_ADDRESS:test}
    password: ${CHEESE_MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false

logging:
    config: classpath:config/logbak.xml

cheese:
  app-name: éBÇÎÇ¡Ç∆É`Å[ÉY
  url: https://www.torochee.com/
  cloud-host-url: ${CHEESE_CLOUD_HOST_URL:https://cdn.torochee.com}
  s3-access-key: ${CHEESE_S3_ACCESS_KEY:}
  s3-secret-key: ${CHEESE_S3_SECRET_KEY:}
  s3-service-end-point: https://s3-ap-northeast-1.amazonaws.com
  s3-region: ap-northeast-1
  s3-bucket: ${CHEESE_S3_BUCKET:}
  timeout: 21600
  slack-app-token: ${CHEESE_SLACK_APP_TOKEN:}
  slack-contact-channel: contact
