spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DATABASE_URL_SPRINGBOOT:jdbc:mysql://localhost:3306/dbname}
    username: ${DATABASE_USER:hogehoge}
    password: ${DATABASE_PASSWORD:fugafuga}
  jackson:
    dateFormat: yyyy/MM/dd HH:mm:ss
    time-zone: Asia/Tokyo

cheese:
  cloud-host-url: https://XXX
  s3-access-key: ${CHEESE_S3_ACCESS_KEY:}
  s3-secret-key: ${CHEESE_S3_SECRET_KEY:}
  s3-service-end-point: https://s3-ap-northeast-1.amazonaws.com
  s3-region: ap-northeast-1
  s3-bucket: ${CHEESE_S3_BUCKET:}
  timeout: 21600
