package com.api.sns.cheese.repository;

import com.api.sns.cheese.domain.TBookmark;
import com.api.sns.cheese.domain.TBookmarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    long countByExample(TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int deleteByExample(TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int insert(TBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int insertSelective(TBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    List<TBookmark> selectByExample(TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    TBookmark selectByPrimaryKey(Long bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBookmark record, @Param("example") TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBookmark record, @Param("example") TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBookmark record);
}