package com.api.sns.cheese.repository;

import com.api.sns.cheese.domain.TFollowTag;
import com.api.sns.cheese.domain.TFollowTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFollowTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    long countByExample(TFollowTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int deleteByExample(TFollowTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long followTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int insert(TFollowTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int insertSelective(TFollowTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    List<TFollowTag> selectByExample(TFollowTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    TFollowTag selectByPrimaryKey(Long followTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFollowTag record, @Param("example") TFollowTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFollowTag record, @Param("example") TFollowTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFollowTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFollowTag record);
}