package com.api.sns.cheese.repository;

import com.api.sns.cheese.domain.TLoginHistory;
import com.api.sns.cheese.domain.TLoginHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLoginHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    long countByExample(TLoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int deleteByExample(TLoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int insert(TLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int insertSelective(TLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    List<TLoginHistory> selectByExample(TLoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    TLoginHistory selectByPrimaryKey(Long historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TLoginHistory record, @Param("example") TLoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TLoginHistory record, @Param("example") TLoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TLoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TLoginHistory record);
}