package com.api.sns.cheese.repository;

import com.api.sns.cheese.domain.TPhotoLike;
import com.api.sns.cheese.domain.TPhotoLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhotoLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    long countByExample(TPhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int deleteByExample(TPhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int insert(TPhotoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int insertSelective(TPhotoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    List<TPhotoLike> selectByExample(TPhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    TPhotoLike selectByPrimaryKey(Long likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhotoLike record, @Param("example") TPhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhotoLike record, @Param("example") TPhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhotoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_like
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhotoLike record);
}