package com.api.sns.cheese.repository;

import com.api.sns.cheese.domain.TPhotoComment;
import com.api.sns.cheese.domain.TPhotoCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPhotoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    long countByExample(TPhotoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int deleteByExample(TPhotoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int insert(TPhotoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int insertSelective(TPhotoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    List<TPhotoComment> selectByExample(TPhotoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    TPhotoComment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPhotoComment record, @Param("example") TPhotoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPhotoComment record, @Param("example") TPhotoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPhotoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPhotoComment record);
}