package com.api.sns.cheese.repository;

import com.api.sns.cheese.domain.TTagPhoto;
import com.api.sns.cheese.domain.TTagPhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTagPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    long countByExample(TTagPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int deleteByExample(TTagPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long tagPhotoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int insert(TTagPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int insertSelective(TTagPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    List<TTagPhoto> selectByExample(TTagPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    TTagPhoto selectByPrimaryKey(Long tagPhotoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTagPhoto record, @Param("example") TTagPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTagPhoto record, @Param("example") TTagPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTagPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTagPhoto record);
}