package com.api.sns.cheese.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

/**
 * HLS変換処理結果
 */
@Data
@DynamoDBTable(tableName = "transcode-result")
public class DTranscodeResult {

	/** ID */
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	/** ファイル名 */
	@DynamoDBAttribute(attributeName = "file_key")
	private String fileKey;

	/** S3 MP4ファイルパス */
	@DynamoDBAttribute(attributeName = "input_key")
	private String inputKey;

	/** S3 HLSファイルパス */
	@DynamoDBAttribute(attributeName = "output_key")
	private String outputKey;

	/** 作成日時 */
	@DynamoDBAttribute(attributeName = "created_at")
	private String createdAt;
}
