package com.api.sns.cheese.domain;

import com.api.sns.cheese.enums.ActivityTypeEnum;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_activity
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TActivity implements Serializable {
    /**
     * Database Column Remarks:
     *   アクティビティID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   アクティビティ種別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.activity_type
     *
     * @mbg.generated
     */
    private ActivityTypeEnum activityType;

    /**
     * Database Column Remarks:
     *   写真ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.photo_id
     *
     * @mbg.generated
     */
    private Long photoId;

    /**
     * Database Column Remarks:
     *   コメントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.comment_id
     *
     * @mbg.generated
     */
    private Long commentId;

    /**
     * Database Column Remarks:
     *   フォローアカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.follow_account_id
     *
     * @mbg.generated
     */
    private Integer followAccountId;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.deleted
     *
     * @mbg.generated
     */
    private String deleted;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.activity_id
     *
     * @return the value of t_activity.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.activity_id
     *
     * @param activityId the value for t_activity.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.account_id
     *
     * @return the value of t_activity.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.account_id
     *
     * @param accountId the value for t_activity.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.activity_type
     *
     * @return the value of t_activity.activity_type
     *
     * @mbg.generated
     */
    public ActivityTypeEnum getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.activity_type
     *
     * @param activityType the value for t_activity.activity_type
     *
     * @mbg.generated
     */
    public void setActivityType(ActivityTypeEnum activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.photo_id
     *
     * @return the value of t_activity.photo_id
     *
     * @mbg.generated
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.photo_id
     *
     * @param photoId the value for t_activity.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.comment_id
     *
     * @return the value of t_activity.comment_id
     *
     * @mbg.generated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.comment_id
     *
     * @param commentId the value for t_activity.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.follow_account_id
     *
     * @return the value of t_activity.follow_account_id
     *
     * @mbg.generated
     */
    public Integer getFollowAccountId() {
        return followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.follow_account_id
     *
     * @param followAccountId the value for t_activity.follow_account_id
     *
     * @mbg.generated
     */
    public void setFollowAccountId(Integer followAccountId) {
        this.followAccountId = followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.deleted
     *
     * @return the value of t_activity.deleted
     *
     * @mbg.generated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.deleted
     *
     * @param deleted the value for t_activity.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.created_at
     *
     * @return the value of t_activity.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.created_at
     *
     * @param createdAt the value for t_activity.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.created_by
     *
     * @return the value of t_activity.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.created_by
     *
     * @param createdBy the value for t_activity.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.updated_at
     *
     * @return the value of t_activity.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.updated_at
     *
     * @param updatedAt the value for t_activity.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.updated_by
     *
     * @return the value of t_activity.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.updated_by
     *
     * @param updatedBy the value for t_activity.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
}