package com.api.sns.cheese.domain;

import com.api.sns.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bookmark
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TBookmarkKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   ブックマークID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.bookmark_id
     *
     * @mbg.generated
     */
    private Long bookmarkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.bookmark_id
     *
     * @return the value of t_bookmark.bookmark_id
     *
     * @mbg.generated
     */
    public Long getBookmarkId() {
        return bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.bookmark_id
     *
     * @param bookmarkId the value for t_bookmark.bookmark_id
     *
     * @mbg.generated
     */
    public void setBookmarkId(Long bookmarkId) {
        this.bookmarkId = bookmarkId;
    }
}