package com.api.sns.cheese.domain;

import com.api.sns.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_follow_tag
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TFollowTagKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   タグフォローID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.follow_tag_id
     *
     * @mbg.generated
     */
    private Long followTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.follow_tag_id
     *
     * @return the value of t_follow_tag.follow_tag_id
     *
     * @mbg.generated
     */
    public Long getFollowTagId() {
        return followTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.follow_tag_id
     *
     * @param followTagId the value for t_follow_tag.follow_tag_id
     *
     * @mbg.generated
     */
    public void setFollowTagId(Long followTagId) {
        this.followTagId = followTagId;
    }
}