package com.api.sns.cheese.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_follow_tag
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TFollowTag implements Serializable {
    /**
     * Database Column Remarks:
     *   タグフォローID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.follow_tag_id
     *
     * @mbg.generated
     */
    private Long followTagId;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   タグID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.tag_id
     *
     * @mbg.generated
     */
    private Long tagId;

    /**
     * Database Column Remarks:
     *   ブロックフラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.block_flag
     *
     * @mbg.generated
     */
    private Boolean blockFlag;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.deleted
     *
     * @mbg.generated
     */
    private String deleted;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow_tag.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_follow_tag
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.follow_tag_id
     *
     * @return the value of t_follow_tag.follow_tag_id
     *
     * @mbg.generated
     */
    public Long getFollowTagId() {
        return followTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.follow_tag_id
     *
     * @param followTagId the value for t_follow_tag.follow_tag_id
     *
     * @mbg.generated
     */
    public void setFollowTagId(Long followTagId) {
        this.followTagId = followTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.account_id
     *
     * @return the value of t_follow_tag.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.account_id
     *
     * @param accountId the value for t_follow_tag.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.tag_id
     *
     * @return the value of t_follow_tag.tag_id
     *
     * @mbg.generated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.tag_id
     *
     * @param tagId the value for t_follow_tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.block_flag
     *
     * @return the value of t_follow_tag.block_flag
     *
     * @mbg.generated
     */
    public Boolean getBlockFlag() {
        return blockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.block_flag
     *
     * @param blockFlag the value for t_follow_tag.block_flag
     *
     * @mbg.generated
     */
    public void setBlockFlag(Boolean blockFlag) {
        this.blockFlag = blockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.deleted
     *
     * @return the value of t_follow_tag.deleted
     *
     * @mbg.generated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.deleted
     *
     * @param deleted the value for t_follow_tag.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.created_at
     *
     * @return the value of t_follow_tag.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.created_at
     *
     * @param createdAt the value for t_follow_tag.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.created_by
     *
     * @return the value of t_follow_tag.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.created_by
     *
     * @param createdBy the value for t_follow_tag.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.updated_at
     *
     * @return the value of t_follow_tag.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.updated_at
     *
     * @param updatedAt the value for t_follow_tag.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow_tag.updated_by
     *
     * @return the value of t_follow_tag.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow_tag.updated_by
     *
     * @param updatedBy the value for t_follow_tag.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
}