package com.api.sns.cheese.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_follow
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TFollow implements Serializable {
    /**
     * Database Column Remarks:
     *   フォローID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.follow_id
     *
     * @mbg.generated
     */
    private Long followId;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   フォローアカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.follow_account_id
     *
     * @mbg.generated
     */
    private Integer followAccountId;

    /**
     * Database Column Remarks:
     *   ブロックフラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.block_flag
     *
     * @mbg.generated
     */
    private Boolean blockFlag;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.deleted
     *
     * @mbg.generated
     */
    private String deleted;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_follow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.follow_id
     *
     * @return the value of t_follow.follow_id
     *
     * @mbg.generated
     */
    public Long getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.follow_id
     *
     * @param followId the value for t_follow.follow_id
     *
     * @mbg.generated
     */
    public void setFollowId(Long followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.account_id
     *
     * @return the value of t_follow.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.account_id
     *
     * @param accountId the value for t_follow.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.follow_account_id
     *
     * @return the value of t_follow.follow_account_id
     *
     * @mbg.generated
     */
    public Integer getFollowAccountId() {
        return followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.follow_account_id
     *
     * @param followAccountId the value for t_follow.follow_account_id
     *
     * @mbg.generated
     */
    public void setFollowAccountId(Integer followAccountId) {
        this.followAccountId = followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.block_flag
     *
     * @return the value of t_follow.block_flag
     *
     * @mbg.generated
     */
    public Boolean getBlockFlag() {
        return blockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.block_flag
     *
     * @param blockFlag the value for t_follow.block_flag
     *
     * @mbg.generated
     */
    public void setBlockFlag(Boolean blockFlag) {
        this.blockFlag = blockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.deleted
     *
     * @return the value of t_follow.deleted
     *
     * @mbg.generated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.deleted
     *
     * @param deleted the value for t_follow.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.created_at
     *
     * @return the value of t_follow.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.created_at
     *
     * @param createdAt the value for t_follow.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.created_by
     *
     * @return the value of t_follow.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.created_by
     *
     * @param createdBy the value for t_follow.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.updated_at
     *
     * @return the value of t_follow.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.updated_at
     *
     * @param updatedAt the value for t_follow.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.updated_by
     *
     * @return the value of t_follow.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.updated_by
     *
     * @param updatedBy the value for t_follow.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
}