package com.api.sns.cheese.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_login_history
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TLoginHistory extends TLoginHistoryKey implements Serializable {
    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_history.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   IPアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_history.ip_address
     *
     * @mbg.generated
     */
    private String ipAddress;

    /**
     * Database Column Remarks:
     *   ユーザーエージェント
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_history.user_agent
     *
     * @mbg.generated
     */
    private String userAgent;

    /**
     * Database Column Remarks:
     *   ホスト
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_history.host
     *
     * @mbg.generated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_login_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_history.account_id
     *
     * @return the value of t_login_history.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_history.account_id
     *
     * @param accountId the value for t_login_history.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_history.ip_address
     *
     * @return the value of t_login_history.ip_address
     *
     * @mbg.generated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_history.ip_address
     *
     * @param ipAddress the value for t_login_history.ip_address
     *
     * @mbg.generated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_history.user_agent
     *
     * @return the value of t_login_history.user_agent
     *
     * @mbg.generated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_history.user_agent
     *
     * @param userAgent the value for t_login_history.user_agent
     *
     * @mbg.generated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_history.host
     *
     * @return the value of t_login_history.host
     *
     * @mbg.generated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_history.host
     *
     * @param host the value for t_login_history.host
     *
     * @mbg.generated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }
}