package com.api.sns.cheese.domain;

import com.api.sns.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_photo
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TPhotoKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   写真ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo.photo_id
     *
     * @mbg.generated
     */
    private Long photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_photo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo.photo_id
     *
     * @return the value of t_photo.photo_id
     *
     * @mbg.generated
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo.photo_id
     *
     * @param photoId the value for t_photo.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }
}