package com.api.sns.cheese.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_photo_comment
 *
 * @mbg.generated do_not_delete_during_merge
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TPhotoComment extends TPhotoCommentKey implements Serializable {
    /**
     * Database Column Remarks:
     *   コメントコード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo_comment.comment_cd
     *
     * @mbg.generated
     */
    private String commentCd;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo_comment.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   写真ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo_comment.photo_id
     *
     * @mbg.generated
     */
    private Long photoId;

    /**
     * Database Column Remarks:
     *   内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo_comment.deleted
     *
     * @mbg.generated
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_photo_comment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo_comment.comment_cd
     *
     * @return the value of t_photo_comment.comment_cd
     *
     * @mbg.generated
     */
    public String getCommentCd() {
        return commentCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo_comment.comment_cd
     *
     * @param commentCd the value for t_photo_comment.comment_cd
     *
     * @mbg.generated
     */
    public void setCommentCd(String commentCd) {
        this.commentCd = commentCd == null ? null : commentCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo_comment.account_id
     *
     * @return the value of t_photo_comment.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo_comment.account_id
     *
     * @param accountId the value for t_photo_comment.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo_comment.photo_id
     *
     * @return the value of t_photo_comment.photo_id
     *
     * @mbg.generated
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo_comment.photo_id
     *
     * @param photoId the value for t_photo_comment.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo_comment.content
     *
     * @return the value of t_photo_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo_comment.content
     *
     * @param content the value for t_photo_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo_comment.deleted
     *
     * @return the value of t_photo_comment.deleted
     *
     * @mbg.generated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo_comment.deleted
     *
     * @param deleted the value for t_photo_comment.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }
}