package com.api.sns.cheese.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_photo
 */
public class TPhotoWithBLOBs extends TPhoto implements Serializable {
    /**
     * Database Column Remarks:
     *   緯度経度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_photo.location
     *
     * @mbg.generated
     */
    private byte[] location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_photo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_photo.location
     *
     * @return the value of t_photo.location
     *
     * @mbg.generated
     */
    public byte[] getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_photo.location
     *
     * @param location the value for t_photo.location
     *
     * @mbg.generated
     */
    public void setLocation(byte[] location) {
        this.location = location;
    }
}