package com.api.sns.cheese.domain;

import com.api.sns.common.business.domain.AbstractBaseEntity;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_tag_photo
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class TTagPhotoKey extends AbstractBaseEntity implements Serializable {
    /**
     * Database Column Remarks:
     *   写真タグID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.tag_photo_id
     *
     * @mbg.generated
     */
    private Long tagPhotoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.tag_photo_id
     *
     * @return the value of t_tag_photo.tag_photo_id
     *
     * @mbg.generated
     */
    public Long getTagPhotoId() {
        return tagPhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.tag_photo_id
     *
     * @param tagPhotoId the value for t_tag_photo.tag_photo_id
     *
     * @mbg.generated
     */
    public void setTagPhotoId(Long tagPhotoId) {
        this.tagPhotoId = tagPhotoId;
    }
}