package com.api.sns.cheese.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_tag_photo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TTagPhoto implements Serializable {
    /**
     * Database Column Remarks:
     *   写真タグID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.tag_photo_id
     *
     * @mbg.generated
     */
    private Long tagPhotoId;

    /**
     * Database Column Remarks:
     *   タグID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.tag_id
     *
     * @mbg.generated
     */
    private Long tagId;

    /**
     * Database Column Remarks:
     *   写真ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.photo_id
     *
     * @mbg.generated
     */
    private Long photoId;

    /**
     * Database Column Remarks:
     *   削除フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.deleted
     *
     * @mbg.generated
     */
    private String deleted;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag_photo.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_tag_photo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.tag_photo_id
     *
     * @return the value of t_tag_photo.tag_photo_id
     *
     * @mbg.generated
     */
    public Long getTagPhotoId() {
        return tagPhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.tag_photo_id
     *
     * @param tagPhotoId the value for t_tag_photo.tag_photo_id
     *
     * @mbg.generated
     */
    public void setTagPhotoId(Long tagPhotoId) {
        this.tagPhotoId = tagPhotoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.tag_id
     *
     * @return the value of t_tag_photo.tag_id
     *
     * @mbg.generated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.tag_id
     *
     * @param tagId the value for t_tag_photo.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.photo_id
     *
     * @return the value of t_tag_photo.photo_id
     *
     * @mbg.generated
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.photo_id
     *
     * @param photoId the value for t_tag_photo.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.deleted
     *
     * @return the value of t_tag_photo.deleted
     *
     * @mbg.generated
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.deleted
     *
     * @param deleted the value for t_tag_photo.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.created_at
     *
     * @return the value of t_tag_photo.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.created_at
     *
     * @param createdAt the value for t_tag_photo.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.created_by
     *
     * @return the value of t_tag_photo.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.created_by
     *
     * @param createdBy the value for t_tag_photo.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.updated_at
     *
     * @return the value of t_tag_photo.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.updated_at
     *
     * @param updatedAt the value for t_tag_photo.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag_photo.updated_by
     *
     * @return the value of t_tag_photo.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag_photo.updated_by
     *
     * @param updatedBy the value for t_tag_photo.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }
}