package com.api.sns.cheese.domain;

import java.io.Serializable;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table v_activity
 *
 * @mbg.generated do_not_delete_during_merge
 */
@EqualsAndHashCode
@ToString
public class VActivity implements Serializable {
    /**
     * Database Column Remarks:
     *   アクティビティID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.activity_id
     *
     * @mbg.generated
     */
    private Long activityId;

    /**
     * Database Column Remarks:
     *   フォローアカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.follow_account_id
     *
     * @mbg.generated
     */
    private Integer followAccountId;

    /**
     * Database Column Remarks:
     *   コメントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.comment_id
     *
     * @mbg.generated
     */
    private Long commentId;

    /**
     * Database Column Remarks:
     *   写真ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.photo_id
     *
     * @mbg.generated
     */
    private Long photoId;

    /**
     * Database Column Remarks:
     *   アカウントID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   アクティビティ種別
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.activity_type
     *
     * @mbg.generated
     */
    private String activityType;

    /**
     * Database Column Remarks:
     *   ログインID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.login_id
     *
     * @mbg.generated
     */
    private String loginId;

    /**
     * Database Column Remarks:
     *   アカウント名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   画像パス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_activity.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_activity
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.activity_id
     *
     * @return the value of v_activity.activity_id
     *
     * @mbg.generated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.activity_id
     *
     * @param activityId the value for v_activity.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.follow_account_id
     *
     * @return the value of v_activity.follow_account_id
     *
     * @mbg.generated
     */
    public Integer getFollowAccountId() {
        return followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.follow_account_id
     *
     * @param followAccountId the value for v_activity.follow_account_id
     *
     * @mbg.generated
     */
    public void setFollowAccountId(Integer followAccountId) {
        this.followAccountId = followAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.comment_id
     *
     * @return the value of v_activity.comment_id
     *
     * @mbg.generated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.comment_id
     *
     * @param commentId the value for v_activity.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.photo_id
     *
     * @return the value of v_activity.photo_id
     *
     * @mbg.generated
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.photo_id
     *
     * @param photoId the value for v_activity.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.account_id
     *
     * @return the value of v_activity.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.account_id
     *
     * @param accountId the value for v_activity.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.activity_type
     *
     * @return the value of v_activity.activity_type
     *
     * @mbg.generated
     */
    public String getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.activity_type
     *
     * @param activityType the value for v_activity.activity_type
     *
     * @mbg.generated
     */
    public void setActivityType(String activityType) {
        this.activityType = activityType == null ? null : activityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.login_id
     *
     * @return the value of v_activity.login_id
     *
     * @mbg.generated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.login_id
     *
     * @param loginId the value for v_activity.login_id
     *
     * @mbg.generated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.name
     *
     * @return the value of v_activity.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.name
     *
     * @param name the value for v_activity.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_activity.img_url
     *
     * @return the value of v_activity.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_activity.img_url
     *
     * @param imgUrl the value for v_activity.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}